apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development-apis
  namespace: default
spec:
  description: A project for managing the development APIs
  destinations:
  - name: '*'
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/jasondeka/application-manifests
