apiVersion: v1
kind: Secret
metadata:
  name: github-jasondeka-applications
  namespace: default
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/jasondeka/application-manifests
